### ISSUE TITLE
Use git submodule for lmdb dependency

### ISSUE THREAD

**Issue by CoreyKaylor** [CoreyKaylor/Lightning.NET#1]
For discussion: It would be nice if the dll wasn't precompiled and committed and rather part of a build script that pulls in the .dll or .so file compiled from the submodule. This will make it easier to pull in and react to changes from the upstream lmdb project. I am happy to cook something up for this. My approach would be to use MinGW and a separate Makefile for the Windows specific dll.

**Comment by ilyalukyanov** [comment]
Corey, a submodule for the native library is a good idea. 
Are you sure a cross-compilation option will be useful? We already have a Makefile to build lmdb on linux and we have MsBuild project to build it on Windows. All we have to do is to include compilation of native binaries into this MsBuild project and compilation og managed dll into the Makefile. Isn't it better to keep it separate? What is your oppinion?
Also, despite these changes, i still want to keep precompiled Windows native library available for download so people who just want to give it a try could get it without downloading sources and compilation. A better solution would be to keep the binaries not in repository but on the dedicated site, but i don't have one.

**Comment by CoreyKaylor** [comment]
I think requiring the VS C++ Project(s) is an extra burden that is unnecessary IMO. I'm also guessing here that the maintainers of the core lmdb library would be more willing to participate in compatibility discussions if it doesn't require them using VS to do so. I would rather include the native.dll in it's own nuget package rather than requiring a separate download. I prefer automation of all the tedious maintenance pieces that by themselves are not that big of a deal, but over the life of an OSS project can get tedious.

For what it's worth I have a copy of the Makefile stripped down for Windows compiling on MinGW and the core project as a submodule. Pretty minimal to maintain.

**Comment by ilyalukyanov** [comment]
Ok, you are right, let's do it. A good strategy, it think, would be to support several build systems. I already have a VS C++ project here - https://github.com/ilyalukyanov/lightningdb-win that was forked from OpenLDAP's repository and modified a little. I will support it anyway as it's necessary for couple of my projects. Sometimes for a developer it could be complicated to install MinGW or a Linux VM. Standard VS project would be convinient in these cases.
My forked lmdb project is designed the way that no changes are done to the main codebase so no merging is required if we want to update sources to an actual lmdb revision.

**Comment by CoreyKaylor** [comment]
Yeah, it's about striking balance between making things as easily available to your users vs. easy as possible to maintain. Nuget makes that story much better than it used to be.

**Comment by CoreyKaylor** [comment]
Closed by 9ca190af1c26edc22be4bf309caa295afaf763a8
