### ISSUE TITLE
Add compability and targets to a solution to compile on *nix

### ISSUE THREAD

**Issue by ilyalukyanov** [CoreyKaylor/Lightning.NET#10]
Currently it is a post build event that runs a command that copies lmdb.dll binary to a LightningDB.Tests/bin directory. The command is windows command and the binary is a windows dll.
Should add a target to a solution that copies liblmdb.so binary to this directory as well as the binary to the repository.

**Comment by CoreyKaylor** [comment]
IMO this should be done in the rakefile and not in the .csproj.

**Comment by ilyalukyanov** [comment]
I agree, when we want to use CI server or just want to get output bins, the correct way is to put this responsibility on the build script. I also want to make IDE integrated automated testing tools available. VS ones run automatically every time you rebuild. If native dll is missing most of tests will fail. Maybe I'm overestimating the problem as in your case we will have to run rake or copy dll manually just once and then be able to develop. I'll try to modify rakefile myself to get some experience with rake.

**Comment by CoreyKaylor** [comment]
One other note, I removed the packages.config as it's duplicating what ripple will already do. Also for mono, it needs to be locked at the version in the ripple.config. They updated NUnit for the async 4.5 features and it broke compatibility.

Even though it's probably a bit unconventional with the larger .NET community I would recommend giving ripple a try. Especially when dealing with multiple platforms.

Ideally IMO you run rake once and your environment is setup to run the tools. It's fairly standard in many open source projects to run the build script before being expected to be able to build or run the tests from within VS.

**Comment by CoreyKaylor** [comment]
I need to tweak the rakefile slightly to ensure the output directory exists before compiling the native assembly. That shouldn't take long, but I'm done for the day. You can check the progress at the url below. For the Windows build I just need to install MinGW on the build server.

http://build.fubu-project.org/project.html?projectId=project63 (register or login as guest)

**Comment by CoreyKaylor** [comment]
This will also give the benefit of having a private nuget feed against the teamcity url. More details to follow after the builds are green.

**Comment by CoreyKaylor** [comment]
The Linux build agent is running now. The tests are still failing for permissions issues. The Windows build agent is now failing because it's compiling 64 bit lmdb.dll and running tests with the 32 bit runner. I'll update fuburake to make it a bit more intelligent about which runner to use to resolve that issue.

**Comment by CoreyKaylor** [comment]
I updated the instructions for [building the project](https://github.com/ilyalukyanov/Lightning.NET/wiki/Building-the-project).

**Comment by CoreyKaylor** [comment]
I've updated fuburake and Lightning with the appropriate changes. The fuburake gem will have to be pushed first, but won't be too long.

This changes things so if you need to compile on x86 (Mono on Mac) you will need to now run `rake platform=x86`

**Comment by ilyalukyanov** [comment]
Hi, Correy, thank you for all the great job you've done. I'll take a close look on it soon... For now i have a huge amount of work to be done. I hope i'll finish it in a week or two.

**Comment by CoreyKaylor** [comment]
The gems have been published and the Windows build is green now. The Linux agent is still failing for permissions issues. I'll come back around to these a little bit down the road I'm sure it's something simple.

**Comment by CoreyKaylor** [comment]
Now that things are slowing down for you, they're getting busier for me... FYI, the CI builds I setup are both broken from the latest changes in master but I haven't had time to check into why.

**Comment by ilyalukyanov** [comment]
Corey, I have an idea why it could happen. I'll check build on linux and
fix this on weekend

2013/10/11 Corey Kaylor notifications@github.com

**Comment by ilyalukyanov** [comment]
Despite i fixed some blocking issues, the problem wasn't caused by them. i686-w64-mingw32-gcc compiler wasn't found by build server (according to build logs). Maybe i should use another one?

**Comment by CoreyKaylor** [comment]
Closing this now for the now travis-ci and appveyor build scripts working.
