### ISSUE TITLE
include runtime for linux

### ISSUE THREAD

**Issue by mihasic** [CoreyKaylor/Lightning.NET#100]
I see that current repository always builds them on travis, but nuget package does not contain the linux binaries.

Could you please include the compiled mdb in the nupkg, so the dependent projects can build easily on linux?

**Comment by CoreyKaylor** [comment]
I'll take pull requests, but given the sheer # of possibilities I don't have time to do this work myself. Feel free to re-open with a PR.

**Comment by smbecker** [comment]
Does this get easier with .net core 2 since linux is treated as a single runtime?

**Comment by CoreyKaylor** [comment]
Possibly?
