### ISSUE TITLE
put fails when called from inside a Parallel.For loop

### ISSUE THREAD

**Issue by undecided2013** [CoreyKaylor/Lightning.NET#107]
App crashes out when the put is called from inside
Parallel.For(0, 100000000, (i) =>
                    {
                    tx.Put(db, BitConverter.GetBytes(i), BitConverter.GetBytes(i), PutOptions.None);
                    }

I was trying some perf tests and I wanted to utilize many cores. I used the code in ProfilingTests.cs. Modified  DoStuffHelper method.

**Comment by CoreyKaylor** [comment]
This is not supported in the underlying lmdb native library so therefore I won't be supporting it here. If you need parallelization, you'll need a unique transaction per thread.
