### ISSUE TITLE
[Suggestion] Surface return codes from Delete and Put

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [CoreyKaylor/Lightning.NET#108]
Reading the lmdb docs i see that `mdb_del` returns `MDB_NOTFOUND` as an indicator that it could find a key to delete.

Similarly `mdb_put` will return ` MDB_KEYEXIST` if there is already a key in the database. 

These hints could be of use to clients and should be surfaced in the API. 

If the maintainer thinks this is a good idea I could put a PR together to add this.

**Comment by CoreyKaylor** [comment]
I'm open to the changes, but I understand that you may not be motivated to help considering I've neglected the project for some time. My circumstances have changed, but I'll leave this open regardless as a reminder.

**Comment by AlgorithmsAreCool** [comment]
Oh wow, I moved on from using this package a while back. But i still think it is by far the easiest to use of the .NET LMDB wrappers. 
Thank you for writing it!

I'm pretty busy for the next few days, but i'll try to submit a simple PR.

**Comment by CoreyKaylor** [comment]
Upon looking into this request further. It looks like all code paths assert the return code and throw a LightningException that includes the status code.
