### ISSUE TITLE
Updating docs

### ISSUE THREAD

**Issue by aliostad** [CoreyKaylor/Lightning.NET#109]
Hi Corey,

Nice work!

Is it ok if I submit a PR for updating README, adding stuff like download/nuget ...? I find that useful to be there as I want to use it and see it would have been good in the docs.

Thanks
Ali

**Comment by CoreyKaylor** [comment]
@aliostad sorry for going dark on you, my work circumstances had changed and I was doing a ton of traveling that left my energy for any extra stuff just non-existent. I'll be updating the repo to some of the latest api changes in .net core and will be open to any docs that help there. I understand if you're no longer interested, but I'll keep the issue open as a reminder for myself regardless.

**Comment by aliostad** [comment]
No worries mate! I know how it is, I also do a bit of OSS and I know how hard is to allocate time to do chores. Keep up the good work!

I will close this for now but great work.
