### ISSUE TITLE
Ripple-cli gem and building on Mac

### ISSUE THREAD

**Issue by ilyalukyanov** [CoreyKaylor/Lightning.NET#11]
While trying to build on Mac I've faced a problem with ripple-cli which is worked around as described [here](https://github.com/ilyalukyanov/Lightning.NET/wiki/Building-on-Mac) I don't like this solution as it's a hack. Maybe there is more straight way to do this?

**Comment by CoreyKaylor** [comment]
Your link isn't working. Can you elaborate a bit more?

**Comment by CoreyKaylor** [comment]
Nevermind, I found the wiki page that was created.

**Comment by CoreyKaylor** [comment]
This is likely a bug with ripple-cli gem itself. It does work on our Ubuntu Linux CI agent. I'll try and track down a fix for the Mac side of things.

**Comment by CoreyKaylor** [comment]
Yeah, this seems to be working on Ubuntu because it associates .exe with mono already. Should have a fix for this soon.

**Comment by ilyalukyanov** [comment]
Ok, thank you. I've fixed the link) not yet familiar with this markdown)

**Comment by CoreyKaylor** [comment]
In the meantime, you can modify the "ripple" file in the installed gem directory to look like this and it will fix your problem.

cmd = ""
if(!RUBY_PLATFORM.match("linux|darwin").nil?)
  cmd << "mono "
end
cmd << File.dirname(**FILE**) + "/ripple.exe " + ARGV.join(' ')

result = system(cmd)
exit 1 unless result

**Comment by CoreyKaylor** [comment]
Okay, the new gem has been published. You'll just need to run 'bundle update'. I have tested that ripple works on both Windows and Mac side now for this project.
