### ISSUE TITLE
Benchmark tests with BenchmarkDotNet

### ISSUE THREAD

**Issue by CoreyKaylor** [CoreyKaylor/Lightning.NET#114]
It would be great to setup some benchmarks and merge them also into the pre-Span as a branch that can be used for comparison.

**Comment by AlgorithmsAreCool** [comment]
I'm also working on this, it only makes sense since the span stuff is all performance oriented.

It is a bit fiddly however because of the native dependency, I'm working through it

**Comment by CoreyKaylor** [comment]
Yeah, it should "just work" from the dotnet cli, but I've found I have to sometimes control the process architecture by using --runtime win-x64. That said, I noticed there's likely a bug in the targets file that copies over the native dependency for x86. I'll try and figure that one out, but in the meantime I would only really worry about x86.

**Comment by AlgorithmsAreCool** [comment]
So the build works fine and the tests all execute a-ok, but BDN does the funky isolation where it builds the projects indirectly during test execution. I think that is messing with something. I'm still troubleshooting it.

**Comment by AlgorithmsAreCool** [comment]
Got it working 👍.
