### ISSUE TITLE
Providers should change to be more extensible

### ISSUE THREAD

**Issue by CoreyKaylor** [CoreyKaylor/Lightning.NET#12]
As it is currently the providers are a bit clumsy relying on static state / extension methods (in a separate namespace). The IL emitting is overly complex and probably unnecessary given what it's doing. I'm spiking an alternative for review including tests. This should also be inline with the future goals of the project to integrate with custom serializers.

This will ultimately boil down to registering converters that deal with something similar to Func<byte[], TTargetType>.

**Comment by ilyalukyanov** [comment]
Corey, in case of default serializer, IL emitting is important to avoid boxing/unboxing. Maybe I've missed something, but it looked for me as the only way to achieve this.

**Comment by CoreyKaylor** [comment]
Call it a theory when I don't have tests to compare against yet, but I'm willing to bet that any potential advantages to avoid boxing is lost in dynamically compiling a delegate. Don't worry though, I'll cover my bases before committing to this route and pushing up a branch for review.

**Comment by ilyalukyanov** [comment]
Corey, i'm not worry. No doubt you know what you are doing. A thing about these delegates is that delegates are compiled only once for each pair of types in AppDomain. Then delegates are used without additional resources cost. And yes, this is a theory without tests.

**Comment by CoreyKaylor** [comment]
Calling this one closed for now. Maybe more things to add, but want to start working towards using the API for real now and flush out some of the friction points.
