### ISSUE TITLE
Assembly Signature Requirements

### ISSUE THREAD

**Issue by cockroach888** [CoreyKaylor/Lightning.NET#132]
你好，很感谢提供了这么好用的类库，在使用过程中，我一般会下载源代码加已分析，然后直接从 NuGet 中获取到版本，并添加到项目引用当中，但由于我的项目都是使用了强签名的，而在 NuGet 中获取到的并没有签名，虽然我可以手动加上一个签名，但这样会造成二次操作，容易在更新时忘记，所以，还是希望从 NuGet 中获致到的版本本身就是带签名的，谢谢。

Hello, thank you for providing such a useful library, in the process of using it, I usually download the source code plus analysis, and then get the version directly from NuGet and add it to the project reference, but because my projects are using a strong signature, and the one obtained in NuGet does not have a signature, although I can add a signature manually, but this will cause a second operation, easy to forget when updating, so, I still hope that the version obtained from NuGet itself is signed, thank you.

Translated with www.DeepL.com/Translator (free version)

**Comment by AlgorithmsAreCool** [comment]
@CoreyKaylor I think they are asking about a strong named assembly? Is that something you think is a good idea?

**Comment by CoreyKaylor** [comment]
I would recommend using something like https://www.nuget.org/packages/StrongNamer/ if you have those kind of requirements. I don't really have an interest right now in signing the assembly.

**Comment by cockroach888** [comment]
thinks.
