### ISSUE TITLE
AsEnumerable fails silently

### ISSUE THREAD

**Issue by Jure-BB** [CoreyKaylor/Lightning.NET#139]
If an error occurs during enumeration when using `AsEnumerable` extension method, enumeration fails silently without reporting an error. 

The reason seems to be that this method only checks for `MDBResultCode.Success` result code and treats all other codes as `MDBResultCode.NotFound`. It should probably throw an exception, if result code is neither `Success` or `NotFound`.

**Comment by AlgorithmsAreCool** [comment]
Taking a look...

**Comment by CoreyKaylor** [comment]
Yes, thanks for reporting. I'll probably remove the if check and provide a convenience extension method to throw on error. That way it's consistent with the rest of the API.

**Comment by CoreyKaylor** [comment]
Take it back, I don't want to change the return type. I'll throw on error instead.
