### ISSUE TITLE
Testcases are missing a check in some places where LightningCursor.GetCurrent() is used

### ISSUE THREAD

**Issue by bartwe** [CoreyKaylor/Lightning.NET#140]
A number of testcases like ShouldAdvanceKeyToClosestWhenKeyNotFound call GetCurrent() but do not assert the result.

**Comment by CoreyKaylor** [comment]
It does use the result. It destructures the result and only selects the key ignoring the other parts of the result. This is sufficient for the test. I reviewed all uses of GetCurrent and found similar outcomes. Let me know if there is a problem you see specifically that I've overlooked.
