### ISSUE TITLE
Linux native binaries not available through NuGet

### ISSUE THREAD

**Issue by TomTondeur** [CoreyKaylor/Lightning.NET#141]
Hi! I am consuming Lightning.NET as a NuGet package and am in the process of porting my .NET Core application to Linux, but this is failing due to `lmdb.so` not being found. It looks like the native Linux binaries I need have been added recently (as seen in https://github.com/CoreyKaylor/Lightning.NET/issues/133) and are available in master. Would it be possible to release a new NuGet version that includes the new binaries?

Many thanks,
Tom

**Comment by CoreyKaylor** [comment]
I have quite a bit going on right now. Moved across the country and several construction projects on our home. It's been hard to find any free time. Before I publish again I wanted to get a newer version of all the binaries. If anybody else can knock that out it would make a brief publish step a lot easier on me.

**Comment by Aaronontheweb** [comment]
Looks like we need to upgrade to 0.9.29 - the most recent included binaries were from 0.9.24 https://github.com/CoreyKaylor/Lightning.NET/pull/137

**Comment by Aaronontheweb** [comment]
I'd probably just do a release with the bits as-is for now. Can always do another one with newer binaries later on.

**Comment by AustEcon** [comment]
I'm having the same issue with use in docker (linux-x64 binaries are missing from the Nuget package, only has linux-arm)

`System.DllNotFoundException: Unable to load shared library 'lmdb' or one of its dependencies`

**Comment by CoreyKaylor** [comment]
https://github.com/CoreyKaylor/Lightning.NET/releases/tag/v0.14.0

**Comment by AustEcon** [comment]
> https://github.com/CoreyKaylor/Lightning.NET/releases/tag/v0.14.0 is published to nuget.org now.

Legend! It all works now for me on linux / docker :) 

Thank you so much :)
