### ISSUE TITLE
Create new Nuget package with https://github.com/CoreyKaylor/Lightning.NET/pull/145 merged

### ISSUE THREAD

**Issue by chris-skuvault** [CoreyKaylor/Lightning.NET#147]
We are switching to use the autoresize dll included in this lib instead of using our own when upgrading to 0.14.0 from 0.13.0. Our tests are failing because of the issue fixed in https://github.com/CoreyKaylor/Lightning.NET/pull/145. 

Can we get an updated NuGet package that contains this change so that we can upgrade to the new version?

**Comment by CoreyKaylor** [comment]
Yes I should have some downtime pretty soon. Just finished with our busiest time of the year.

**Comment by CoreyKaylor** [comment]
Included in 0.14.1
