### ISSUE TITLE
[Windows/.NET 6.0] Can't open Environments where the Path contains special characters

### ISSUE THREAD

**Issue by Sonix** [CoreyKaylor/Lightning.NET#162]
**OS:** Windows 10 Pro 
**.NET Runtime:** 6.0.315

### Description
Trying to open an Environment in a Path with special characters like 'ß' fails on Windows.

### Testcase
```
    public void CanOpenEnvironmentWithSpecialCharacters()
    {
        _env = new LightningEnvironment(Path.Combine(Path.GetTempPath(), "Testß"));

        _env.Open();
    }
```

### Workaround / Fix
Manually convert the string to a bayte[9 before calling the native DLL works, like this:

`var bytes = Encoding.UTF8.GetBytes(path);`

I'll open a Pull Request with the change that works for me in a minute.

**Comment by Sonix** [comment]
@CoreyKaylor Hi, is there a possibility for a bugfix release from your side which contains this change? I can also work with a local fork until your next regular release but if one does happen anyway I'd save myself the extra effort :) Thanks!

**Comment by CoreyKaylor** [comment]
I'll try and get something out this weekend. It's a busy week for me at work.

**Comment by Sonix** [comment]
Cool, thanks alot! No pressure though, its not *that* urgent :)
