### ISSUE TITLE
LightningEnvironment.CopyTo Corruption

### ISSUE THREAD

**Issue by DecoyFish** [CoreyKaylor/Lightning.NET#165]
We've encountered a case in which a DB saved via [LightningEnvironment.CopyTo](https://github.com/CoreyKaylor/Lightning.NET/blob/a24534a904a7a5fe21d6f272fe2a984def80f3c5/src/LightningDB/LightningEnvironment.cs#L248) was corrupted.  Looking at the code, this method calls [Lmdb.mdb_env_copy2](https://github.com/CoreyKaylor/Lightning.NET/blob/a24534a904a7a5fe21d6f272fe2a984def80f3c5/src/LightningDB/Native/Lmdb.cs#L89), but doesn't appear to do anything with the returned result code.  Is this by design (as there might be no viable way for this to fail), or should CopyTo return a MDBResultCode?

**Comment by AlgorithmsAreCool** [comment]
I've never used this function, but disregarding the return code doesn't seem like correct behavior. We should probably change it to throw on a failing return code.

**Comment by DecoyFish** [comment]
Thanks, I've opened the following PR with the change and a test: #166

**Comment by CoreyKaylor** [comment]
Thanks, PR is merged and sorry for the hiatus. I've had quite a lot going on in my personal life lately.

**Comment by DecoyFish** [comment]
No worries.  Thanks for maintaining this awesome project.
