### ISSUE TITLE
Why is not Put method in Transaction?

### ISSUE THREAD

**Issue by Bobris** [CoreyKaylor/Lightning.NET#17]
It is not logical that Put is on Database object. You don't want to create new database when you create new transaction you want to reuse existing Database object.

Or can you create slightly bigger sample how multiple transactions to same database could be done. Some of them should be writing some of them read-only.

I tried workaround with cursor (but it crashes on access violation):

```
        var env = new LightningEnvironment("db", EnvironmentOpenFlags.None);
        env.Open();
        var txn = env.BeginTransaction();
        var db = txn.OpenDatabase(null, DatabaseOpenFlags.None);
        txn.Commit();
        txn.Dispose();

        var rnd = new Random(1234);
        for (int j = 0; j < 1000; j++)
        {
            txn = env.BeginTransaction();
            var cursor = new LightningCursor(db, txn);
            for (int i = 0; i < 1000; i++)
            {
                var key = new byte[rnd.Next(10, 50)];
                rnd.NextBytes(key);
                var value = new byte[rnd.Next(50, 500)];
                rnd.NextBytes(value);
                cursor.Put(key, value, PutOptions.None);
            }
            cursor.Close();
            cursor.Dispose();
            txn.Commit();
            txn.Dispose();
        }
        db.Close();
        db.Dispose();
        env.Close();
        env.Dispose();
```

**Comment by ilyalukyanov** [comment]
Boris,
LightningDB transactions and databases are slightly not the same as RDBMS ones. What we call Database in Relational world is Environment in lightning, database in lightning is closer to table in RDBMS.
In relational database you don't query database itself but you query tables.
Also this reflects [lightning native API](http://symas.com/mdb/doc/group__mdb.html). Sure, managed API should be more convenient and abstract and it's the further goal.
In lightning we open database in a transaction, when transaction is disposed all databases opened inside of it and it's child transactions are closed too. There always should be opened root transaction. That's why you get access violation in your scenario. Of course I should add more specific handling for such cases. 
Nevertheless you've spotted lack of API support. We should be allowed to reuse database opened in parent transaction in it's child transactions.. I will definitely reconsider the API to make this achievable.
When I finish I'll give you an example with new API.

**Comment by Bobris** [comment]
I am very aware of this difference. I written my own NoSQL pure .Net Key Value storage https://github.com/Bobris/BTDB which I want to compare speed to LMDB.

Also if you look at:

```
mdb_get (MDB_txn *txn, MDB_dbi dbi, MDB_val *key, MDB_val *data)
```

You see that txn is first parameter which actually in "C" language usually emulates OOP. MDB_dbi is just integer - it is very lightweight because you can think of it just as first part of key.

Child transactions are nearly useless feature as I understand them. And they don't use them in their benchmarks:
http://symas.com/mdb/microbench/db_bench_mdb.cc

So thanks that you will try to improve it.

**Comment by ilyalukyanov** [comment]
Boris,
First of all, I was wrong about dbs and transactions [according to this](http://symas.com/mdb/doc/group__mdb.html#gac08cad5b096925642ca359a6d6f0562a), db handle can be reused after transaction commits. So your example revealed a bug in a wrapper. I will fix it.

Actually both first and second arguments of mdb_get are handles corresponding to unmanaged resources. We could treat each of them as "this". 
I think it's ok to call db-access methods from transaction object, moreover if it's convenient. Ideally we will come to smth like this: `txn.Get("db_name", "key")`. But there are things to think about, for example db_name to handle lookups which cost perforemance.

I'm not motivating you to use child transactions, i'm just saying that this feature is supported by the native API for any purpose so the managed one should support it too so it could be used even if in rare cases.

I'll solve this issue as the next major feature in roadmap. Thank you for valuable feedback!

**Comment by Bobris** [comment]
I am all for speed so first parameter in txn.Get should be LightingDatabase object from which you will just extract MDB_dbi and call mdb_get. 
I would be also for removing that "Lazy" in https://github.com/ilyalukyanov/Lightning.NET/blob/master/src/LightningDB/MarshalValueStructure.cs#L9 and move actual code into getter itself (less allocations and synchronization on hot functions). You don't need to be thread safe because LMDB is also not thread safe (in sense you cannot have 2 transactions in same thread, or transaction cannot move to next thread). That's BTW huge limitation because it means you cannot use async in .Net on thread pool with opened write transaction, but I still want to compare speed :-) and don't want to wait until https://github.com/ayende/raven.voron will be finished.

**Comment by ilyalukyanov** [comment]
Boris,

Removing Lazy is reasonable. This disposable is never shared between threads.
Lightning [can](http://symas.com/mdb/doc/group__mdb.html#gad7ea55da06b77513609efebd44b26920) share read-only transactions between threads. But yes there are some limitations. They don't look very huge for me as in async-await scenarios you can always start a new transaction (it should be fast but benchmarks are required).

I'll try to do these changes this evening.
Once you will be done with your comparison, please share the results for me, the ayre very interesting for me.

**Comment by Bobris** [comment]
I will try to publish benchmark code on Github. It would be nice if that version would be on Nuget. And have 64bit lmdb.dll bundled. Thanks again.
