### ISSUE TITLE
Accessing database statistics when opened via committed transaction

### ISSUE THREAD

**Issue by DecoyFish** [CoreyKaylor/Lightning.NET#176]
When updating to the latest release, I noticed the *`.Handle()` methods were removed.  It's totally reasonable to abstract these potential foot-guns.  However, our project was previously using these to fetch DB statistics (via `Lmdb.mdb_stats`) for DBs that were opened in a committed transaction (and then reused by later transactions).  The open/reuse case is similar to this test:
https://github.com/CoreyKaylor/Lightning.NET/blob/37dedf441651ce4c38ecc72bf9875eb691fb7858/src/LightningDB.Tests/DatabaseTests.cs#L48

In the spirit of the recent change, I'd like to add a method to `LightningTransaction` like:
```csharp
public Stats GetStats(LightningDatabase db) {...}
```

PS: Thanks for for the updates on and active maintenance of this project

**Comment by DecoyFish** [comment]
I've opened the following PR with the change and tests: https://github.com/CoreyKaylor/Lightning.NET/pull/177

**Comment by CoreyKaylor** [comment]
Thank you for the PR. I should be able to review and merge in this weekend.

**Comment by CoreyKaylor** [comment]
Closed by https://github.com/CoreyKaylor/Lightning.NET/pull/177
