### ISSUE TITLE
Convert tests to NUnit for easier testing on Mono

### ISSUE THREAD

**Issue by CoreyKaylor** [CoreyKaylor/Lightning.NET#2]
I would like to setup a CI build for both Windows and Mono testing and to make the tests as easy as possible to run on both I would like to convert them to use NUnit. Also changing up the way some of them are written to eliminate the race condition failures that happen when running in a batch. Thoughts?

**Comment by ilyalukyanov** [comment]
Corey, seems reasonable. I've developed this library with only VS and windows in mind. A good improvement would be to achieve testability on both platforms, moreover it's crucial for CI.

**Comment by CoreyKaylor** [comment]
I've made some headway on this and the other items as well. I should be able to push up another pull request for review tonight.

After a few of these have gone over well with you I will probably leverage the commit access and not do the pull requests unless more discussion is needed for something.
