### ISSUE TITLE
VS Express 2010 - build/run problems

### ISSUE THREAD

**Issue by bertbeck** [CoreyKaylor/Lightning.NET#22]
I just downloaded the current release and tried to build using VS Express 2010. I had to remove a reference to "CommonAssembly.cs:in the VS solution to make it build. Once I did it built ok.  I created a test project to run a few unit tests.

My test project fails with a "dll load error" saying it can't find lmdb32. I have taken this file from the Binary directory and added it to all projects - but still no luck,

I am running on windows8.

Any suggestions ?

**Comment by ilyalukyanov** [comment]
Hello, if you want to just use the library, i'd suggest to use a [nuget package](http://www.nuget.org/packages/LightningDB/).

Unfortunately you can't just download the sources and build it in VS. First of all you should install a build environment with rake, mingw/msys, etc. Then, after building a project with rake, you will be able to freely work with VS solution without any additional changes as it becomes properly configured by the build script.

Natives in Binaries directory aren't guaranteed to be normally built. So i'd suggest to use ones from nuget package.

It could be time consuming task to install the environment. If this is what you want, i'll be glad to provide a guide for you.
