### ISSUE TITLE
LightningEnvironment.MapDatabases should be named MaxDatabases

### ISSUE THREAD

**Issue by nblumhardt** [CoreyKaylor/Lightning.NET#23]
https://github.com/ilyalukyanov/Lightning.NET/blob/master/src/LightningDB/LightningEnvironment.cs#L98

Typo in the property name - should probably be `MaxDatabases`.

Regards,
Nick

**Comment by ilyalukyanov** [comment]
Definitely! Thank you, i'll fix it untill tomorrow

**Comment by nblumhardt** [comment]
You're welcome, thanks for the interesting project, I'm looking forward to spending some time learning the API.

(There's also a typo in the name of `LightningTransacrionState`.)

Cheers!

**Comment by nblumhardt** [comment]
("Close" and "Comment" buttons too close to one another, sorry :).)
