### ISSUE TITLE
Nuget package needs updating

### ISSUE THREAD

**Issue by jhashemi** [CoreyKaylor/Lightning.NET#26]
started investigating why i was getting MDB_MAP_FULL: Environment mapsize limit reached, and when I looked at the repo's lightningenviroment its different then what came from nuget ;-)

**Comment by ilyalukyanov** [comment]
My bad. I'll publish the new version in the next 24 hours =)

**Comment by ilyalukyanov** [comment]
It's done. New version is available on NuGet - https://www.nuget.org/packages/LightningDB/
