### ISSUE TITLE
NuGet package does not contain xml comments

### ISSUE THREAD

**Issue by configurator** [CoreyKaylor/Lightning.NET#27]
Apparently the XML comment file was not generated when compiling for NuGet, meaning the library is undocumented in VS unless you link directly to the source. It's a shame, too, because the source code is very well documented.

**Comment by ilyalukyanov** [comment]
Thank you, It worked and sorry for the delay. The next goal is to cover the remaining classes and members with docs. I've scheduled this to the next weekend.

**Comment by ilyalukyanov** [comment]
In the comment to your commit I've noticed that you have problems building the project. Is there anything I can help you with?

**Comment by configurator** [comment]
Thanks, but I'm sure I could figure it out, I just don't really need to
build it myself so I didn't spend the time.

**Comment by ilyalukyanov** [comment]
I've just finished adding the documentation for each public member in the library. As I've also added some new API and made some refactoring, once I properly test these changes, I'll publish the new version into NuGet. This is going to take for a couple of days.

**Comment by ronnieoverby** [comment]
I'm looking forward to this too.

**Comment by ilyalukyanov** [comment]
It's there. Sorry for the delay.
