### ISSUE TITLE
Cross platform build script

### ISSUE THREAD

**Issue by CoreyKaylor** [CoreyKaylor/Lightning.NET#3]
I would like to setup a build script preferably using rake so that cross platform compilation and testing is as easy as possible. I'm happy to do this. Thoughts?

**Comment by CoreyKaylor** [comment]
If it helps, we already have a CI server and several examples of running CI mode on both *nix and Windows.

http://build.fubu-project.org/ (Login as guest)

**Comment by ilyalukyanov** [comment]
I'm not against rake, but what are the benefits over make (except syntactic ones)? As we've discussed in issue #1 there will be a single Makefile. If so, what tasks are you planning to automize with it? Would it be an additional build system? Would it be self-contained or utilizing Makefiles?

**Comment by CoreyKaylor** [comment]
The rakefile is where it will all end up. Compile lmdb both on Windows and *nix and may or may not delegate to the existing Makefile (I'm leaning towards not doing so). It will also compile the .NET projects, run tests, create nuget packages, build "live docs"??, and a manual task to do the publish explicitly. It is syntactic to some degree, but with the benefits of a full blown scripting language at your disposal. It also comes with the benefit that most of the things I mentioned above are a solved problem using rake in our existing OSS projects and I would have to re-learn everything about make.

**Comment by ilyalukyanov** [comment]
Corey, i see now. Rake is the tool you have experience with. Ok, lets do it with rake at first. Then, once i get some free time, i will add autoconf and make support and then we'll decide what to do next.

**Comment by CoreyKaylor** [comment]
I'll move on to the rest of this and the submodule issue soon. I'll probably be distracted until later in the week though.

**Comment by CoreyKaylor** [comment]
Quick update: Shocking that this is a bit more challenging than expected. Looks like the build script will be custom for Windows, Mac, and Linux because on macs the native assembly extension is .dylib, and on Linux is .so. Also, at first glance there will need to be a custom .dll.config depending on the platform using dllmap. http://www.mono-project.com/Interop_with_Native_Libraries#Library_Names

I'm still working on it, but might be a bit longer until I have something workable on each.

**Comment by CoreyKaylor** [comment]
The config file for dllmap is not necessary as I first thought. The problem was obscure and ended up being that mono requires 32 bit on a Mac so it was failing to import the 64 bit compiled .dylib file.

Now I'm down to permission denied errors coming from the lmdb code that I need to track down. Hopefully after that I'll have a recipe that can work across platforms.

**Comment by CoreyKaylor** [comment]
"sudo rake" is working on MacOS. For some reason though it keeps getting the permission denied errors inside the lmdb code. I'm doing this all within my user profile, so there _shouldn't_ be an issue, but I'll keep trying to track it down.

I may still call this a temporary victory to continue with the rakefile changes tomorrow.

**Comment by ilyalukyanov** [comment]
Corey, yes, as i can remember dll remapping is not necessary in this case, Mono will fallback library names using different sufixes and prefixes.
Which lmdb function invokes permission denied error? Maybe it's due to 666 access mode hard coded in [LightningEnvironment.Open](https://github.com/ilyalukyanov/Lightning.NET/blob/master/src/LightningDB/LightningEnvironment.cs#L118)?

**Comment by CoreyKaylor** [comment]
That could be a likely cause. Regardless, I think I'm going to get a script going that is easy without copying files around and then look into this. Surprisingly though the tests all do pass, although the coverage is still lacking a bit.

**Comment by CoreyKaylor** [comment]
Okay, I have a working native compile w/rakefile and submodule for lmdb on Mac. I'll finish things off for Windows and Linux tomorrow sometime. I still haven't looked into the permission issues.

**Comment by CoreyKaylor** [comment]
Closed by 9ca190af1c26edc22be4bf309caa295afaf763a8
