### ISSUE TITLE
Problems with attached debugger (64-bit LMDB only)

### ISSUE THREAD

**Issue by runaum** [CoreyKaylor/Lightning.NET#31]
http://pastebin.com/XW5ej3pa - this (and not only this) example frequently crashed (on ~300k iteration) on two machines, when debugger is attached. Some examples crashes (on both machines too) earlier.

Tested with VS2013, lmdb binaries from NuGet package and binaries builded from VS. Without debugger - all is ok.

Can you confirm this problem?

I'm sorry for my 'MGIMO finished' English.

**Comment by ilyalukyanov** [comment]
I will check this in my environment. It could be an expected behavior as the debugger may intercept operations with memory in a specific way. I'm on the business trip right now, but I will try to check this ASAP

**Comment by runaum** [comment]
I think, that I located this problem. .Net can load Dll in any time, for example in time when few threads are already exists, but Dll knows nothing about them - so DLL_THREAD_ATTACH will not called for them or something like this. 

We need to check mdb sources for:
1. Any function with TLS operations need to call TlsGetValue, check for 0, if true - initiate TLS with TlsSetValue.
2. Check TlsGetValue for 0 in DLL_THREAD_DETACH

I'll try to do it, but I don't sure in it. I'm sorry for my English, Ilya.

UPDATE: For first look it was fixed now - https://gitorious.org/mdb/mdb/merge_requests/3. May be some other problems with TLS, but one hour testing - no crashes now. It will be a good idea to check this problem and the solution from your side too.

**Comment by ilyalukyanov** [comment]
Many thanks, your investigation is very helpful. I'm sorry for not paying enough attention to your problem - I have a horribly busy period. This issue is of maximum priority for my nearest free time.

**Comment by runaum** [comment]
This problem fixed. My merge request was successfully [commited](https://gitorious.org/mdb/mdb/commit/a93810cc3d1a062bf5edbe9c14795d0360cda8a4) into main repo by Howard Chu.

For everyone, who got this problem: I recommend to build lmdb32/64 from Ilya's [repository](https://github.com/ilyalukyanov/lightningdb-win) with updated mdb library from official [repository](https://gitorious.org/mdb/mdb).

**Comment by ilyalukyanov** [comment]
Thank you! I have published the version 0.8.3 on nuget with native binaries updated to the latest version.
