### ISSUE TITLE
Unable to load lmdb64.dll in web apps

### ISSUE THREAD

**Issue by ronnyek** [CoreyKaylor/Lightning.NET#35]
I got an error in a web application complaining the wrappers could not load the 64bit dll, which I was able to remedy by fiddling around with the permissions on the files...

Do you know if there is a reason this was the case (increased security requirements in web applications?)

I installed via nuget.

**Comment by ilyalukyanov** [comment]
Hi,

It's weird... I couldn't reproduce this. Could you please provide an example project deomnstrating the issue? I would be glad to fix this.

**Comment by CoreyKaylor** [comment]
Tested and worked for me.
