### ISSUE TITLE
Test fails with provided binaries

### ISSUE THREAD

**Issue by buybackoff** [CoreyKaylor/Lightning.NET#36]
On my machine  CursorShouldDeleteElements fails when I clone the repo and run.

It deletes key1 and key3, not key2. I have updated source to 0.9.14 and recompiled the binaries using your lightningdb-win project and the test started to pass.

**Comment by buybackoff** [comment]
NuGet package is OK

**Comment by buybackoff** [comment]
When I run all tests at once (with NuGet's or new 0.9.14 binaries), some tests fail randomly with 

`SetUp : LMDB.LightningException : Input/output error
   at LMDB.Native.NativeMethods.ExecuteHelper(Func`2 action, Func`2 shouldThrow) in Native.cs: line 130
   at LMDB.LightningEnvironment.Open() in LightningEnvironment.cs: line 173`

Similar stuff was with C++ tests, sometimes they failed when the time between two runs was very small. My (uneducated guess) is that it is related to acquiring lock (in C tests the error was around there) - probably DB is being closed/opened too fast and lock file is not synced.

Error messages are cryptic. Is it possible to make some error enumeration on .NET side?

**Comment by ilyalukyanov** [comment]
Binaries contained in the repo might be inproperly build. They look old and I don't remember when I last updated them :) 

Binaries from the NuGet package are more recent and cross-compiled from the official repo without any changes so they are better. I'll update the submodule and explore what's happening,

**Comment by buybackoff** [comment]
It looks like in NuGet they are DEBUG now. People will love you if you give them a ready-to-go updated Windows release build :) This is such a pain to do it manually.

**Comment by ilyalukyanov** [comment]
I'm working on it right now) Was busy for a while moving to another country) Now nothing distracts me)

**Comment by ilyalukyanov** [comment]
The release 0.8.5.51145 is out. Should be available in NuGet soon. I've updated binaries in the repo as well.

**Comment by ilyalukyanov** [comment]
I think I can closs it. Please feel free to reopen if you still have issues.
