### ISSUE TITLE
mdb_set_compare is missing

### ISSUE THREAD

**Issue by buybackoff** [CoreyKaylor/Lightning.NET#39]
This is very useful. E.g. I want to map 1-to-1 [SortedList<K,V>](http://msdn.microsoft.com/en-us/library/ms132319%28v=vs.110%29.aspx) to a named DB to make it persistent. And I have a struct that has custom comparison (not a string and not an integer) and I use it as a key very often.

**Comment by ilyalukyanov** [comment]
Good point! Implemented it in master. Implementation is a bit dirty. Not sure if the final implementation will be the same. But it works =)

**Comment by buybackoff** [comment]
Cool! I didn't know for sure how to deal with native calls for this. Thank you!

If I understand B+-trees correctly, the compare function is used for writes to find insert location and for searches, and we need log(n) comparisons for each operations. Each comparison requires two marshallings of ValueStructs and then two deserializations - that could be costly and random read/write will suffer. But MoveNext/Prev don't use comparison at all and Append uses single comparison with the last value.

**Comment by ilyalukyanov** [comment]
You are slightly mixing different things, if I understand you correctly. O(log(n)) - is a meajure that shows how time (complexity) of tree search grows with the number of elements. The comparison function doesn't depend on the number of tree elements, so it's O(const), hence we still have O(log(n)).

I'd estimate the comparison function's complexity as O(m), where m - key/value length, but it's not important.

Of course, you're right that the function's performance suck and it will defenitely decrease performance  by a constant value. I'm thinking of adding an overload that accepts a function pointer so a caller could provide anything (for instance, a native func). This should negate the problem.

**Comment by CoreyKaylor** [comment]
I've made some changes to the original implementation in the dnx branch. Now you just need to specify in the options for a db an IComparer<byte[]> you want to use for comparison.

There's more room for improvement performance-wise but the impelementation is a bit cleaner and I have ideas for speeding up the performance across the board.

**Comment by CoreyKaylor** [comment]
Issue I'm proposing regarding performance enhancements. https://github.com/ilyalukyanov/Lightning.NET/issues/57

**Comment by CoreyKaylor** [comment]
There is enough here to call this closed for now. Performance optimizations can be a separate effort, but the set comparison options in LightningConfiguration will now be used if provided.
