### ISSUE TITLE
Add support for key range lookup

### ISSUE THREAD

**Issue by CoreyKaylor** [CoreyKaylor/Lightning.NET#4]
I didn't see that there was support yet for key range lookups?

**Comment by ilyalukyanov** [comment]
Hm, maybe i've missed it. Can't you please point to the concrete API in the lmdb docs?

**Comment by CoreyKaylor** [comment]
The main page states "Ordered-map interface (keys are always sorted, supports range lookups)" http://symas.com/mdb/

I believe it is the Cursor API. It looks like you have preliminary code to use cursors, but not tested, nor is it leveraging the "key" to start the range lookup. Or at least that's my understanding thus far. Might be worth taking a look at leveldb-sharp's API because they have a similar capability.

http://symas.com/mdb/doc/group__mdb.html#ga48df35fb102536b32dfbb801a47b4cb0

**Comment by ilyalukyanov** [comment]
Corey, i assume it's about MDB_SET_RANGE option support in mdb_cursor_get, and, yes, .NET API doesn't allow to specify a key for this cursor operation. Also it lacks testing as you've mentioned. I think i will refactor LightningCursor.Get method to avoid explicit CursorOperation argument providing. It should become a set of fluent methods - one for each (or for a group) of enum's flags.

**Comment by CoreyKaylor** [comment]
Yeah, if I'm understanding what you're saying clearly I like exposing methods as opposed to the options parameter on the cursor.

**Comment by ilyalukyanov** [comment]
Yes, you are correct, i'll do exactly this.
