### ISSUE TITLE
Option DuplicateSort should not be in put options

### ISSUE THREAD

**Issue by buybackoff** [CoreyKaylor/Lightning.NET#40]
[This option `DuplicateSort = 0x04`](https://github.com/ilyalukyanov/Lightning.NET/blob/master/src/LightningDB/PutOptions.cs#L26) is only for DB open and is misleading, I tried to use it instead of `None` when Intellisense showed enum members and couldn't understood why I got AccessViolation.

`StoreMultiple = 0x80000` - should be in CursorPutOptions, not in PutOptions

http://symas.com/mdb/doc/group__mdb.html#ga1f83ccb40011837ff37cc32be01ad91e

**Comment by ilyalukyanov** [comment]
You are right, thanks! It feels that native api slightly changed since I first implemented the librariy's P/Invoke part. Or just a mistake. Will fix.
