### ISSUE TITLE
Default Converters are not "symmetrical"

### ISSUE THREAD

**Issue by KarolKolenda** [CoreyKaylor/Lightning.NET#42]
Is there a reason why converters predefined in DefaultConverters are not "paired"?
There is plenty ConvertFromBytes instances but only few ConvertToBytes. For instance Int64 or byte[] converters need to be added explicitly if someone wants to use them.

**Comment by ilyalukyanov** [comment]
Cannot remember my thinking as this was implemented too long ago, but looks like it's a bug =)
