### ISSUE TITLE
Accessing database from read-only transaction

### ISSUE THREAD

**Issue by KarolKolenda** [CoreyKaylor/Lightning.NET#43]
First of all - this is not a bug. Let's assume we have LMDB directory with "tab" database already created by the previous execution of our process. According to LMDB spec the following use case is not valid:

```
        LightningDB.LightningEnvironment env = new LightningEnvironment(@"c:\8\");
        env.Open();

        using (var transaction = env.BeginTransaction(TransactionBeginFlags.ReadOnly))
        {
            var database = transaction.OpenDatabase("tab");
            string buf;
            transaction.TryGet(database, 2, out buf);  //First time - everything is OK
        }

        using (var transaction = env.BeginTransaction(TransactionBeginFlags.ReadOnly))
        {
            var database = transaction.OpenDatabase("tab");
            string buf;
            transaction.TryGet(database, 2, out buf);  //Second time - invalid parameter exception
        }
```

LMDB says that database handles should be reused which is what Lightning.NET is doing flawlessly but it also states that the first call for database handle should be performed from writeable transaction. If the aforementioned code will first open database from an empty writeable transaction, everything would be fine. Saying all that it took me a whole day tracking down this problem.

Question: can we somehow protect the user from shooting herself in the foot for instance by raising a descriptive exception when the first OpenDatabase call to obtain a handle is made from ReadOnly transaction?

**Comment by CoreyKaylor** [comment]
I've changed the internals in my fork to not require all the manager classes and instead rely on events to handle coordination of lifecycles between the various objects that need to do so. This makes it so LightningDB doesn't shoot your foot for you, but doesn't prevent you from shooting your own foot which IMO is a decent compromise.

**Comment by CoreyKaylor** [comment]
Leaving this open for now because I've removed the ability for the databases to be reused across transactions at the moment. I'll close when I revisit that effort to again allow reuse.

**Comment by CoreyKaylor** [comment]
Okay, I've pushed a change to the dnx branch that allows for reuse of the database across transactions again. Calling this one good.
