### ISSUE TITLE
Doc for Cursor.Put is out of date, could be misleading; excessive marshalling

### ISSUE THREAD

**Issue by buybackoff** [CoreyKaylor/Lightning.NET#45]
Compare [this line](https://github.com/ilyalukyanov/Lightning.NET/blob/master/src/LightningDB/LightningCursor.cs#L254)

with the [current docs](http://symas.com/mdb/doc/group__mdb.html#ga1f83ccb40011837ff37cc32be01ad91e):

> This function stores key/data pairs into the database. The cursor is positioned at the new item, or on failure usually near it. Note: Earlier documentation incorrectly said errors would leave the state of the cursor unchanged.

In addition, currently there is no way to move cursor without marshalling both keys and values. There are valid use cases when one would want to skip value marshalling, e.g. LINQ-like First/Where(predicate) search or accessing lagged items with N MovePrev (here even key marshalling is not needed if we want a lagged value `V(i-n)` for a key `K(i)`).

The same is true for [collections](https://github.com/ilyalukyanov/Lightning.NET/blob/master/src/LightningDB/Collections/CursorEnumerator.cs#L40), since they just use the same cursor.Get() where marshalling happens.

Enumerator.MoveNext uses MoveNext, so even with .Skip(N) all N values are marshalled.

```

public static CursorGetByOperation MoveNextBy(this Cursor cur)
        {
            return CursorMoveBy(cur, cur.MoveNext);
        }
```

Lazy marshalling could be useful because it is more or less expensive operation, especially for non-trivial keys/values.

There is [one thing](http://symas.com/mdb/doc/group__mdb.html#structMDB__val) to keep in mind with lazy marshalling, but currently it is irrelevant because marshalling always happens after any move:

> Values returned from the database are valid only until a subsequent update operation, or the end of the transaction.

An [example](https://github.com/dw/py-lmdb/commit/fcfdb28bc74fd6f8c9bdb2a36c122c7738cb237b#diff-460c23bd0a8d65c4566caee15576732bR327) in py-lmdb.

**Comment by ilyalukyanov** [comment]
Agree, this is a necessary improvement. Will fix in future, more likely after the DNX changes are merged.

**Comment by CoreyKaylor** [comment]
This should already be improved in the dnx branch now. I've made all the marshaling in the cursor lazy and also optimized for when we already know the current key and or value.

**Comment by CoreyKaylor** [comment]
I also changed the way that all of the write-side marshaling is happening. It now uses GCHandle.Alloc instead of Marshal.Copy because everything we're marshaling is already blittable so it will use the byte[] as is. The read-side still requires the Marshal.Copy for now.

**Comment by CoreyKaylor** [comment]
Cursor marshaling is now lazy and the comment has been updated in the dnx branch. Calling this one closed.
