### ISSUE TITLE
How to get the database open flag before open

### ISSUE THREAD

**Issue by creambun** [CoreyKaylor/Lightning.NET#50]
Hi there, I'm a newbie on Lightning .Net. I appreciate any help and/or comment

Can someone please give some hint to me if it is possible to know the open flags used to create a database? As a part of my learning, I am trying to list out all databases defined in a given folder and whether they allow duplicate or not

Here is my sample code in C#. In the first part I created an environment and "table1" and put 1 record to it. Then in the second part I pretend that I don't know if "table1" supports duplicate or not and try to read the "entry". How can I tell if "table1" supports duplicate or not?

Any comments are highly appreciated

Cheers,
Creambun

//===============================
Encoding enc = Encoding.UTF8;
const string STR_DATA_FOLDER_PATH = @"C:\temp\testData\DbFlag";

// creating the environment
using (var env = new LightningEnvironment(STR_DATA_FOLDER_PATH))
{
    env.MapSize = 1024 \* 1024 \* 1024;
    env.MaxDatabases = 100000;
    env.MaxReaders = 10;

```
env.Open();

using (var txn = env.BeginTransaction())
{
    // create table "table1"
    using (var db = txn.OpenDatabase("table1", new DatabaseOptions { Encoding = enc, Flags = DatabaseOpenFlags.Create }))
    {
        // add 1 record into "table1"
        txn.Put(db, enc.GetBytes("Key1"), enc.GetBytes("Value1"));
        txn.Commit();

        db.Close();
        db.Dispose();
    }

    txn.Dispose();
}

env.Close();
env.Dispose();
```

}

// read back from the environment
using (var env = new LightningEnvironment(STR_DATA_FOLDER_PATH, EnvironmentOpenFlags.ReadOnly))
{
    env.MapSize = 1024 \* 1024 \* 1024;
    env.MaxDatabases = 100000;
    env.MaxReaders = 10;

```
env.Open();

using (var txn = env.BeginTransaction(TransactionBeginFlags.ReadOnly))
{
    using (var db = txn.OpenDatabase(null, new DatabaseOptions { Encoding = Encoding.UTF8, Flags = DatabaseOpenFlags.None }))
    {
        // so db is the "master" db that contains all database names
        Assert.AreEqual(1, txn.GetEntriesCount(db));

        // I use a cursor to loop through all existing database "entries"
        using (var cursor = txn.CreateCursor(db))
        {
            var kvPair = cursor.MoveNext();
            Assert.IsNotNull(kvPair);
            Assert.IsTrue(kvPair.HasValue);

            // the name of my only database
            Assert.AreEqual("table1", enc.GetString(kvPair.Value.Key));

            // How can I convert "b" into the "DatabaseOpenFlags"?
            // I want to know if it is a database supporting duplicate or not
            byte[] b = kvPair.Value.Value;
        }
    }
}
```

}

**Comment by CoreyKaylor** [comment]
The documentation for lmdb only mentions storing the names so I'm assuming that's all the information you'll find, but I could be wrong.

**Comment by creambun** [comment]
Thanks CoreyKaylor. I appreciate your comment. In that case, I am wondering how can LMDB tell which database is capable of storing duplicates? Any comments are welcome

**Comment by ilyalukyanov** [comment]
I'm just guessing, but I'm slmost sure this is true. I think it cannot and this is applications' concern.

By specifiing flags you only tell lmdb how to work with a binary file or its part (as far as I know a DB is just a subtree inside the file). Nothing stops you from opening a DB with duplicates support, then persisting several duplicates and then reopening without the support, however I suspect this might cause an error.

**Comment by creambun** [comment]
Thank you very much guys. As opinions seem to be a landslide, I guess I would definitely take note of it in my future apps

I'll try to look at the LMDB C source code after I learn C (very hard for me) when I have time in the future and share if I can discover something suggesting otherwise

Thank you all again. Until then, happy coding :)
