### ISSUE TITLE
Proposal: Get rid of Converters

### ISSUE THREAD

**Issue by CoreyKaylor** [CoreyKaylor/Lightning.NET#51]
I don't think they add a lot of value and add to quite a bit of complexity in the code-base throughout. The value provided can be simple extension method in the project that consumes this API.

**Comment by ilyalukyanov** [comment]
Yeah, I agree. I also was thinking about splitting them out into separate NuGet package.

**Comment by CoreyKaylor** [comment]
Will close this issue when it gets merged in. 0b385c5

**Comment by CoreyKaylor** [comment]
Closing in preparation of the dnx branch merge tomorrow.
