### ISSUE TITLE
Proposal: Additional Unsafe nuget LightningDBFast

### ISSUE THREAD

**Issue by CoreyKaylor** [CoreyKaylor/Lightning.NET#57]
For those that can run in full-trust. We can squeeze out every ounce of performance by avoiding Marshal.Copy altogether. I have spiked out a simple example off the dnx branch that would create a new assembly / nuget and allow us to segment unsafe and safe code without creating too much of a maintenance burden through a combination of partial classes and wildcard patterns in project.json. In one instance it will include all *.cs + *.Safe.cs - *.Unsafe.cs, and  the faster dll would include *.cs + *.Unsafe.cs - *.Safe.cs. Normally this would have made me puke to think about, but in the new dnx world this is very trivial to support.

Hopefully everything I've mentioned makes sense?

**Comment by ilyalukyanov** [comment]
Yep makes perfect sense.

**Comment by CoreyKaylor** [comment]
I'm thinking that instead another option might be to provide a func that reads the bytes from the native lib that by default uses the Marshal.Copy and alternatively can be provided a func that uses unsafe calls to optimize for performance. This will reduce the downstream lib dependency conflicts between different nuget dependencies.

**Comment by CoreyKaylor** [comment]
I spiked out several different approaches to this and Marshal.Copy performed better than every one of them. Going to close this unless someone comes up with a better approach.
