### ISSUE TITLE
DRY up the code

### ISSUE THREAD

**Issue by CoreyKaylor** [CoreyKaylor/Lightning.NET#6]
The Marshal'ing of values back and forth could be reduced to something implementing IDisposable as one example. I'll take a crack and submit a pull request first. I realize this type of thing is subjective, but I'll do my best not to step on your toes.

**Comment by ilyalukyanov** [comment]
Corey, thanks for a good remark, i think i understand what you mean. It's definitely a thing for refactoring. If you already have started this refactoring so i'm waiting to pull it. If not, please tell me and i will fix it myself as it's my misdesign.

**Comment by CoreyKaylor** [comment]
I have already started, but I should have something by end of day today to push public for review. A wise man once told me it's a lot easier to come in and fix things after someone already did all the hard work. Also nice to have a another pair of eyes looking at things.

**Comment by ilyalukyanov** [comment]
Ok, Corey, thank you!
