### ISSUE TITLE
Getting "MDB_MAP_FULL: Environment mapsize limit reached" while writing new data

### ISSUE THREAD

**Issue by danielkornev** [CoreyKaylor/Lightning.NET#63]
It seems like we are adding way too much data (JSON documents - metadata) asynchronously and we don't give LMDB a chance to grow its mapsize.

Our write pattern isn't stable; our system (Zet Universe) writes a lot when new data is being added and processed by a variety of data processors, but then it remains silent, ready for its user to look at data.

What could be done to avoid this error?

Thanks,
Daniel

**Comment by danielkornev** [comment]
I've read this thread to better understand the problem with MapSize - https://github.com/CoreyKaylor/Lightning.NET/issues/32 - but still can't figure out what should be put here. In official docs its said that we should put OS page size (10485760), and multiply it to increase the page size. When not setting the map size, we get default value for env.MapSize equal to 0 which is strange. 

When setting it to 1GB, our app crashes. With 512MB, our app can't work, as well.

**Comment by CoreyKaylor** [comment]
When you set it to 1GB does it crash with MDB_MAP_FULL? Or is it another problem? Also, when you say "asynchronously", how are you doing this. LMDB requires exactly one thread per transaction. If using async await you can't guarantee it will be on a single thread.

**Comment by danielkornev** [comment]
Well, ok, I've tried to set it to 1GB by setting env.MapSize to 

**1073741824**

I've got this exception:

`"Not enough storage is available to process this command.\r\n"`

Stack trace:

`at LightningDB.Native.Lmdb.check(Int32 statusCode)
   at LightningDB.Native.Lmdb.mdb_env_open(IntPtr env, String path, EnvironmentOpenFlags flags, UnixAccessMode mode)
   at LightningDB.LightningEnvironment.Open(EnvironmentOpenFlags openFlags, UnixAccessMode accessMode)
   at ZU.Storage.LightningDBStorageProvider.PrepareLightningEnvironment() in C:\stuff\dev\zu_src\ZU\ZU.Storage.LightningDBStorageProvider\LightningDBStorageProvider.DBLayer.cs:line 24
   at ZU.Storage.LightningDBStorageProvider.Load() in C:\stuff\dev\zu_src\ZU\ZU.Storage.LightningDBStorageProvider\LightningDBStorageProvider.Load.cs:line 43
   at ZU.Storage.StorageContext.Load() in C:\stuff\dev\zu_src\ZU.Core\Storage\StorageContext.Load.cs:line 35`

(the rest is omitted)

**Comment by danielkornev** [comment]
Hmm, each time we do write or we do read, we create new transaction, do what we need, and close the transaction.

At the same time we can run more than one Write or Read operation. Does it mean we should have a some sort of a queue to control writes? what about reads?

**Comment by CoreyKaylor** [comment]
I'm not prescribing how you control writes or reads, just commenting that a transaction can only be on one thread, not a single thread at a time, but one thread. Docs also say that a thread can have at most one transaction at a time. How you organize things is up to you.

I assume you've tried 768, that is if you really don't have 1 GB of space available?

**Comment by CoreyKaylor** [comment]
http://symas.com/mdb/doc/group__mdb.html#gad7ea55da06b77513609efebd44b26920

**Comment by danielkornev** [comment]
768MB, 512MB - same there, `Not enough storage is available to process this command.`

**Comment by danielkornev** [comment]
Hmm, I think it's important to note that we run several independent Lightning Environments within our app. Users can create multiple projects (for data integration, visualization, and analysis), and each such project has its own separate database. Maybe this is a problem? 

Typical user can have from 0-10 to hundreds of projects on his computer.

**Comment by CoreyKaylor** [comment]
It could be depending on how much space you take up for each new environment.

**Comment by CoreyKaylor** [comment]
However, are all the environments pointed to the same storage location?

**Comment by danielkornev** [comment]
Different folders on the same disk. As far as I understand, env.MapSize is in bytes, am I right? Judging by the DB size, am I right that default DB size is 1MB?

**Comment by CoreyKaylor** [comment]
Yes, it's in bytes.

**Comment by CoreyKaylor** [comment]
I tend to do stuff like this if it helps. https://github.com/LightningQueues/LightningQueues/blob/dnx/src/LightningQueues.Storage.LMDB/LmdbMessageStore.cs#L24

**Comment by CoreyKaylor** [comment]
Time for the family, I'll be back online tomorrow. There's also use gitter for easier conversation.

**Comment by danielkornev** [comment]
@CoreyKaylor - thanks a lot for your comments. I use the same thing (1024 \* 1024 \* 512) ;) 

I'll take a look at Gitter ) Have a good evening with family!

**Comment by buybackoff** [comment]
@danielkornev use LMDB master build with automatic file resizing on Windows, set the size to 1TB or anything above your free space, and stop worrying about actual file size of an environment. Only available free space on disk will matter then. And multiple environment will compete for it, not reserve space in advance.

**Comment by CoreyKaylor** [comment]
Latest nuget has the updated binaries. I haven't used the auto-grow capabilities yet, but it should be there now.
https://www.nuget.org/packages/LightningDB/0.9.3-rc1-45

**Comment by danielkornev** [comment]
thanks @buybackoff and @CoreyKaylor!
