### ISSUE TITLE
Usability - BeginTransaction() before Open() causes an access violation

### ISSUE THREAD

**Issue by nblumhardt** [CoreyKaylor/Lightning.NET#65]
If `LightningEnvironment.BeginTransaction()` is called before `Open()` a crash results.

``` csharp
            var env = new LightningEnvironment("C:\\Somewhere");
            env.MapSize = 12345;
            env.BeginTransaction();
```

I know there are probably many places where the library or LMDB might behave this way, but since this one is "right at the start" and may discourage new users it seems like checking `Environment.IsOpen` in `BeginTransaction()` and throwing appropriately would be worthwhile.

**Comment by CoreyKaylor** [comment]
I agree, I'll plan for this change as well when I get to my next round of updates.
