### ISSUE TITLE
How to limit RAM usage by the LMDB

### ISSUE THREAD

**Issue by jakoss** [CoreyKaylor/Lightning.NET#67]
I'm trying to build quite big database in LMDB (about 560 M keys in one database, we got 3 databases). Also - while building we need to read some already saved data. So append mode can't be use in our case. The problem is - in about 30% of build progress our RAM usage hit the limit, screen shows the issue:

![Screen of issue](http://i.imgur.com/5oiAaux.jpg)

So my question is - can i limit size of memory that LMDB can use? This database is only test one - for 70k "datasets". On production we will have to store about 3,4 M datasets. Every dataset needs to store 8k keys.

We are looking for SSD-optimized solution, with lowest RAM usage as possible

**Comment by CoreyKaylor** [comment]
Hope this helps.

http://lmdb.readthedocs.io/en/release/#memory-usage
