### ISSUE TITLE
Not compatible on mono since update

### ISSUE THREAD

**Issue by unrealwill** [CoreyKaylor/Lightning.NET#70]
Hello, 
I'm on ubuntu 14.04, running mono/.net 4.5 
All is working fine under mono with version 0.9.2.40, a version I got from nuget.
But the version 0.9.3.0 doesn't target mono/.net 4.5 only .Net framework, so I can't update nor install from nuget now.

Thank you

**Comment by CoreyKaylor** [comment]
What version of mono are you using?

**Comment by CoreyKaylor** [comment]
I'll go ahead and change the target to net45 and push up a new nuget, but I'm surprised that mono at this point doesn't handle the net451 and net452 monikers. I'll dig in further when I have more time.

**Comment by CoreyKaylor** [comment]
https://www.nuget.org/packages/LightningDB/0.9.4

**Comment by unrealwill** [comment]
Wonderful. It works nice. Thank you very much.

**Comment by CoreyKaylor** [comment]
Looks like the next release of mono will work with netstandard packages. At that time I will probably target only netstandard.
