### ISSUE TITLE
Arm support

### ISSUE THREAD

**Issue by valeriob** [CoreyKaylor/Lightning.NET#73]
Do you think it's possible to make it work for ARM ? With the intent to use it on xamarin Android and IOS.

**Comment by CoreyKaylor** [comment]
In theory yes, but I haven't tested this myself.

**Comment by valeriob** [comment]
Maybe leave it open so someone can attempt to  ? :smile:

**Comment by valeriob** [comment]
I hope #103 completes this 😄

**Comment by CoreyKaylor** [comment]
Good deal, I'll see if I can pull this in over Thanksgiving weekend and get a new build published.

**Comment by valeriob** [comment]
Awesome @CoreyKaylor !

**Comment by CoreyKaylor** [comment]
Published 0.10.0 today. There's a problem with the travis ci build, but I'm sure it's regarding changes in the core cli stuff as I haven't touched it in a while. I'll have to revisit that another time.

Thanks for this PR!
