### ISSUE TITLE
Issue about dependencies

### ISSUE THREAD

**Issue by hey-red** [CoreyKaylor/Lightning.NET#76]
Hello! I see you set mappings in [this project](https://github.com/CoreyKaylor/Lightning.NET/blob/master/src/LightningDB/project.json#L19) instead adding Lmdb package as dependency.
It fixes dotnet-cli bug or what?

**Comment by CoreyKaylor** [comment]
Yes, when running locally via the projects the dotnet cli doesn't load the native binaries like it did in earlier rc releases. That is just a workaround to deal with that. Otherwise the nuget package that is released will work fine with the nuget packages included native libs from the dotnet cli.
