### ISSUE TITLE
Incorrect behavior of method LightningEnvironment.Open

### ISSUE THREAD

**Issue by ilyalatt** [CoreyKaylor/Lightning.NET#78]
LightningEnvironment.Open incorrectly handle case when argument openFlags contains EnvironmentOpenFlags.NoSubDir.

> MDB_NOSUBDIR By default, LMDB creates its environment in a directory whose pathname is given in path, and creates its data and lock files under that directory. With this option, path is used as-is for the database main data file. The database lock file is the path with "-lock" appended.

**Comment by DanielAdolfsson** [comment]
Yeah this is breaking things for me.
Need me to submit a patch? It's one line of code to check for the flag.

**Comment by CoreyKaylor** [comment]
A pull request would certainly speed up the fix, yes.

**Comment by CoreyKaylor** [comment]
Thanks for the PR!
