### ISSUE TITLE
Library for windows server 2012?

### ISSUE THREAD

**Issue by qed-** [CoreyKaylor/Lightning.NET#81]
I get a BadImageFormatException trying to use the included (windows 7) libraries on Windows Server 2012.

**Comment by CoreyKaylor** [comment]
Typically that will be due to running the wrong native lib x64 or x86. Are you sure you're using the right one for the architecture your application is running under?

**Comment by qed-** [comment]
64 bit works fine on Windows 10. On server 2012 It works with the 32 bit DLL, despite it being a 64 bit process (not any CPU) on a 64 bit OS. , Not entirely sure what's going on but most likely a problem with my environment, thanks.
