### ISSUE TITLE
Stream interface

### ISSUE THREAD

**Issue by lbergnehr** [CoreyKaylor/Lightning.NET#83]
In order to avoid keeping large chunks of data in memory at the same time as well as making it easier to store really large objects, it would be nice to provide a `Stream` interface to reading and putting data to the database. 

Moreover, instead of copying the data with `Marshal.Copy`, would it be possible to use something like [UnmanagedMemoryStream](https://msdn.microsoft.com/en-us/library/system.io.unmanagedmemorystream(v=vs.110).aspx) instead, avoiding copying the data at all?

**Comment by CoreyKaylor** [comment]
I like the proposal on this issue. https://github.com/CoreyKaylor/Lightning.NET/issues/85

Regarding the UnmanagedMemoryStream I saw worse performance using it over the straight Marshal.Copy. That doesn't mean that a combination of the two possibly wouldn't get us to a better place. Again, happy to take a PR for this especially if it can demonstrably gain perf benefits.

**Comment by CoreyKaylor** [comment]
https://github.com/dotnet/corefx/issues/18946

This API might provide what we need to achieve something of this nature.

**Comment by CoreyKaylor** [comment]
Closing in favor of https://github.com/CoreyKaylor/Lightning.NET/issues/110
