### ISSUE TITLE
lmdb.dll issues

### ISSUE THREAD

**Issue by chriswithpants** [CoreyKaylor/Lightning.NET#87]
I'm attempting to get a simple console application running. I've copied some sample code, installed the nuget package, and when running get an exception saying that it can't find lmdb.dll.

I have tried compiling both x86 and x64. No difference.

Manually copying lmdb.dll into the Debug directory gives a BadImageFormat exception when it's accessed.

Sample Visual Studio project attached. Same issue when trying to run in LINQPad.
[LightningTest.zip](https://github.com/CoreyKaylor/Lightning.NET/files/665655/LightningTest.zip)

Thoughts?

**Comment by nblumhardt** [comment]
Heya @chriswithpants - there's a fully-working app in this repo: https://github.com/datalust/seq-forwarder - may be useful to work backwards from. HTH! 👍

**Comment by chriswithpants** [comment]
Cheers @nblumhardt I'll take a look.

**Comment by chriswithpants** [comment]
I've tested with the dll from @nblumhardt's project and it works fine.

And now, after a good night's sleep, the x64 dll included in the nuget package is working fine. Let's put this one down to tired eyes. Thanks all.
