### ISSUE TITLE
Unable to load DLL 'lmdb': The specified module could not be found

### ISSUE THREAD

**Issue by Horusiath** [CoreyKaylor/Lightning.NET#92]
LightningDB installed via NuGet installs several versions of lmdb.dll in *./packages/runtimes/os/native* path, however they are not copied to build directory. If it's not a bug, it should be at least stated explicitly with the path, where this library could be found.

**Comment by CoreyKaylor** [comment]
When running under coreclr the runtime automatically loads libs at this path. Unfortunately, I don't have plans to go beyond that.

**Comment by CoreyKaylor** [comment]
Looks like there is a PR in that will hopefully fix this in non-coreclr scenarios as well. I'll try to get this in with a new release in the next week or so. https://github.com/CoreyKaylor/Lightning.NET/pull/93

**Comment by CoreyKaylor** [comment]
Closed via be15808
Again, I'll try and publish the nuget before the weekend is over.
